### ISSUE TITLE
generated file is empty

### ISSUE THREAD

**Issue by yairEO** [johnturingan/gulp-html-to-json#2]
```
gulp.src('./views/templates/**/*.html')
    .pipe(htmltojson({
        filename          : "templates.js",
        useAsVariable     : true,
        prefix            : "yourprefix"
    }))
    .pipe(gulp.dest('./js/dist/'))
```

This gives me a file with on the below content:

```
var templates.js={}
```

I know for sure the files exist. this setup had worked flawlessly with another lib that does the same..

**Comment by Tommassissimo** [comment]
I was confused by the gulp configuration until found this useful issue, thanks a lot guys!

**Comment by johnturingan** [comment]
No worries mate! :) Feel free to comment if you find some issues and we'll fix it. Thanks

**Comment by timrobertson100** [comment]
Thanks for this.  I followed the instructions and also ended up with a {} in the final result until I found this issue.  

Might it be helpful to provide a working example in a github /demo?

**Comment by johnturingan** [comment]
thanks @timrobertson100, you're right, that would be helpful. Will create one.
