### ISSUE TITLE
TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by paulopmx** [johnturingan/gulp-html-to-json#4]
Hey John,

What's up?

Upgrading to 0.1.7 is causing issues for us. I had to downgrade to 0.1.5.

running it creates an extra file, and then this happens:
TypeError: Cannot read property 'filename' of undefined

It was fix after I downgraded.

**Comment by johnturingan** [comment]
Hi Sir @paulopmx 

Sorry bout that! I overlooked 1 method for extracting filename. Forgot to add failsafe condition.

Anyways thank you so much for letting me know! ;) I really appreciate it.
